### ISSUE TITLE
Cache: Deserialization is broken

### ISSUE THREAD

**Issue by 8masterofpuppets8** [GraffiTab/GraffiTab-Android-SDK#22]
Deserializing cached objects is broken when testing on device. This call generates a `LinkedTreeMap` rather than the expected type `T`:

```
Type typeOfT = new TypeToken<T>() {}.getType();
return gson.fromJson(json, typeOfT);
```

**Comment by dfernandezm** [comment]
I was taking an initial look (still without running the app). Initially, the type information looks enough as `TypeToken` does some magic inferring the Type from the parameter (like it does with `loggedInUserCache`. It is worth debugging using the app / simulator to see the actual value of `T` which should be `GTUser` (if it worked...) in both cases as the SharedPrefs are the same and it is the same type of cache/case. 

The problematic call might be the following in `performJsonRequest`:

```
resolveCallFromCacheIfPossible(call.getApiEndpointUrl(), responseHandler, shouldUseCache, isGetRequest);
```

which is not passing in any type information. One test would be using `TypeToken` here to infer the `Type` from the incoming `T` (from `Call<Map<String,T>>`,  not the returning one) and pass it into the workflow (check with debug if it is the correct one, if it is `?` we are in no luck...).

If you could check this, it would discard a couple of scenarios, we'll discuss it when I'm back anyway.

**Comment by 8masterofpuppets8** [comment]
Sounds like that might be the case. I will do some more debugging to investigate and let you know.

**Comment by 8masterofpuppets8** [comment]
http://stackoverflow.com/questions/14139437/java-type-generic-as-argument-for-gson

Looks like we need a class type here. I'll add it and move on, no point to waste more time on this issue I think.
